### ISSUE TITLE
Fatal error: Cannot convert object to primitive... on "Add a card" method

### ISSUE THREAD

**Issue by roboli** [flowxo/flowxo-services-trello-example#2]
Hi there!

I was doing the integration test and I was stuck with this error. I founded that the profile object inside the credentials.json was the problem, just removing it solve it.  So I guess the request call in client.js does not like additional info for oauth.

Tell me if you want me to do a pull request or I'm missing something...

**Comment by fiznool** [comment]
@roboli thanks for submitting this issue.

I can't replicate this on my local setup. Could you run the integration test with `grunt run --stack` and post the stacktrace here? I'll then take a look.

**Comment by fiznool** [comment]
Looking again at the code, we pass the [entire `credentials` object](https://github.com/flowxo/flowxo-services-trello-example/blob/1a6befe2f88136c158ef316d3eb2f08cb71a5d86/lib/client.js#L43) in as the `oauth` parameter to the request. Each key in this object is then [enumerated by the `request` library](https://github.com/request/request/blob/d4b976170aad29b2ec34a9127defad67f062a4f2/lib/oauth.js#L18). So I can see that having the `user_profile` key being passed in is not the best plan.

I'll fix this so that we only pull out the data we need.
